# Generated by Django 5.1.4 on 2025-01-30 07:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='Questions',
            field=tinymce.models.HTMLField(default='', help_text='Add all the Questions to be answered by the candidate'),
        ),
    ]
