# Generated by Django 5.1.4 on 2025-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_listing_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='Questions',
            field=models.TextField(default='', help_text='Add all the Questions to be answered by the candidate'),
        ),
    ]
