# Generated by Django 5.1.4 on 2025-02-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_listing_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='Required_skills',
        ),
        migrations.RenameField(
            model_name='job_listing',
            old_name='Years_of_Experience_Required',
            new_name='Max_Years_of_Experience_Required',
        ),
        migrations.AddField(
            model_name='job_listing',
            name='Min_Years_of_Experience_Required',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Certifications',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Client_Name',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Educational_Qualifications',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Experience_level',
            field=models.CharField(blank=True, choices=[('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior-level', 'Senior-level'), ('Manager', 'Manager'), ('Leadership / CXO', 'Leadership / CXO')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Number_of_Openings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Other_Benefits',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Salary_Range',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='skill',
        ),
        migrations.AddField(
            model_name='job_listing',
            name='Required_skills',
            field=models.TextField(default='Html'),
            preserve_default=False,
        ),
    ]
