# Generated by Django 5.1.4 on 2025-02-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_listing_required_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='Salary_Range',
        ),
        migrations.AddField(
            model_name='job_listing',
            name='Max_Salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_listing',
            name='Min_Salary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Max_Years_of_Experience_Required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Min_Years_of_Experience_Required',
            field=models.PositiveIntegerField(),
        ),
    ]
