# Generated by Django 5.1.4 on 2025-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_listing_salary_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='Number_of_Openings',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
