# Generated by Django 5.1.4 on 2025-02-19 15:28

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_listing_number_of_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_listing',
            name='Certifications',
            field=models.TextField(blank=True, default='', help_text='differentiate with a comma. example object1, object2', null=True, verbose_name='Certifications'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Client_Industry',
            field=models.CharField(max_length=2000, verbose_name='Client Industry'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Client_Name',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Educational_Qualifications',
            field=models.CharField(blank=True, default='', help_text='differentiate with a comma. example object1, object2', max_length=2000, null=True, verbose_name='Education Qualifications'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Employment_type',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Freelance', 'Freelance')], default='Full-Time', max_length=300, verbose_name='Employment type'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Experience_level',
            field=models.CharField(blank=True, choices=[('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior-level', 'Senior-level'), ('Manager', 'Manager'), ('Leadership / CXO', 'Leadership / CXO')], default='', max_length=300, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Job_Description',
            field=tinymce.models.HTMLField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Job_Location',
            field=models.CharField(max_length=2000, verbose_name='Job Location'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Max_Salary',
            field=models.PositiveIntegerField(help_text='only positive integers allowed', verbose_name='Max Salary'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Max_Years_of_Experience_Required',
            field=models.PositiveIntegerField(help_text='only positive integers allowed', verbose_name='Max Years of Experience'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Min_Salary',
            field=models.PositiveIntegerField(help_text='only positive integers allowed', verbose_name='Min Salary'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Min_Years_of_Experience_Required',
            field=models.PositiveIntegerField(help_text='only positive integers allowed', verbose_name='Min Years of Experience'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Number_of_Openings',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='only positive integers allowed', verbose_name='Number of Openings'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Other_Benefits',
            field=models.CharField(blank=True, default='', max_length=2000, null=True, verbose_name='Other Benefits'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Questions',
            field=models.TextField(default='', help_text='Add all the Questions to be answered by the candidate. differentiate with a comma. example object1, object2', verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Required_skills',
            field=models.TextField(help_text='differentiate with a comma. example object1, object2', verbose_name='Required Skills'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='job_listing',
            name='Work_Mode',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-site', max_length=300, verbose_name='Work Mode'),
        ),
    ]
