# Generated by Django 5.1.4 on 2025-02-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_currency_remove_job_listing_salary_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='Currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jobs.currency'),
            preserve_default=False,
        ),
    ]
