# Generated by Django 5.1.4 on 2025-06-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_job_listing_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='Destination_email',
            field=models.EmailField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
