# Generated by Django 5.1.4 on 2025-06-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_listing_destination_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_listing',
            old_name='Destination_email',
            new_name='Requiter_email',
        ),
    ]
