# Generated by Django 5.1.4 on 2025-07-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_destination_email_job_listing_requiter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_listing',
            old_name='Requiter_email',
            new_name='Recruiter_email',
        ),
    ]
