# Generated by Django 5.1.4 on 2024-12-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('service1_heading', models.CharField(max_length=2500)),
                ('service1_description', models.CharField(max_length=2500)),
                ('service1_image_url', models.URLField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
