# Generated by Django 5.1.4 on 2024-12-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service2_description',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='service',
            name='service2_heading',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='service',
            name='service2_image_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='service3_description',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='service',
            name='service3_heading',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='service',
            name='service3_image_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='service4_description',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='service',
            name='service4_heading',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='service',
            name='service4_image_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='service',
            name='service1_description',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='service',
            name='service1_heading',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='service',
            name='service1_image_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
