# Generated by Django 5.1.4 on 2024-12-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0003_uniquesellingpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service1_description',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service1_heading',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service2_description',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service2_heading',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service3_description',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service3_heading',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service4_description',
        ),
        migrations.RemoveField(
            model_name='uniquesellingpoints',
            name='service4_heading',
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='description1',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='description2',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='description3',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='description4',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='heading1',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='heading2',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='heading3',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AddField(
            model_name='uniquesellingpoints',
            name='heading4',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
