# Generated by Django 5.1.4 on 2024-12-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0004_remove_uniquesellingpoints_service1_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=5000)),
                ('heading1', models.CharField(default='', max_length=2500)),
                ('description1', models.CharField(default='', max_length=2500)),
                ('heading2', models.CharField(default='', max_length=2500)),
                ('description2', models.CharField(default='', max_length=2500)),
                ('heading3', models.CharField(default='', max_length=2500)),
                ('description3', models.CharField(default='', max_length=2500)),
                ('heading4', models.CharField(default='', max_length=2500)),
                ('description4', models.CharField(default='', max_length=2500)),
                ('image_url', models.URLField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
