# Generated by Django 5.1.4 on 2024-12-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0005_organizationalstructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1 - Serivice'},
        ),
    ]
