# Generated by Django 5.1.4 on 2024-12-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0006_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationalstructure',
            options={'verbose_name': '3 - Organizational Structure'},
        ),
        migrations.AlterModelOptions(
            name='uniquesellingpoints',
            options={'verbose_name': '2 - Unique Selling Points'},
        ),
    ]
