# Generated by Django 5.1.4 on 2024-12-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0008_clientsdescription_globalexpansion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('logo_url', models.URLField(default='', max_length=255)),
            ],
            options={
                'verbose_name': '6 - Clients Logos',
            },
        ),
    ]
