# Generated by Django 5.1.4 on 2024-12-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0009_clientslogos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientslogos',
            options={'verbose_name': '6 - Clients Logo'},
        ),
        migrations.AlterModelOptions(
            name='uniquesellingpoints',
            options={'verbose_name': '2 - Unique Selling Point'},
        ),
    ]
