# Generated by Django 5.1.4 on 2025-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0010_alter_clientslogos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurStatisics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '3 - Our Statistics',
            },
        ),
        migrations.DeleteModel(
            name='ClientsDescription',
        ),
        migrations.DeleteModel(
            name='OrganizationalStructure',
        ),
        migrations.DeleteModel(
            name='UniqueSellingPoints',
        ),
        migrations.AlterModelOptions(
            name='clientslogos',
            options={'verbose_name': '6 - Clients Logos'},
        ),
        migrations.AlterModelOptions(
            name='globalexpansion',
            options={'verbose_name': '2 - Global Expansion Description'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1 - Serivice Names and Images'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service1_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service2_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service3_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service4_description',
        ),
    ]
