# Generated by Django 5.1.4 on 2025-01-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0011_ourstatisics_delete_clientsdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsAroundtheWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': '2 - Operations Around the World',
            },
        ),
        migrations.CreateModel(
            name='OurStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4000)),
                ('ClientsServed', models.IntegerField()),
                ('CandidatesPlaced', models.IntegerField()),
                ('ClientRetentionRate', models.IntegerField()),
                ('TurnAroundTime', models.IntegerField()),
                ('JoiningRatio', models.IntegerField()),
                ('CandidateSatisfactionRate', models.IntegerField()),
            ],
            options={
                'verbose_name': '3 - Our Statistics',
            },
        ),
        migrations.AlterModelOptions(
            name='clientslogos',
            options={'verbose_name': '4 - Our Clients'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1 - Range of Services'},
        ),
    ]
