# Generated by Django 5.1.4 on 2025-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0012_operationsaroundtheworld_ourstatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='', max_length=255)),
            ],
            options={
                'verbose_name': '4 - Our Clients',
            },
        ),
    ]
