# Generated by Django 5.1.4 on 2025-01-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0013_clientsresponses'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalexpansion',
            name='i',
            field=models.IntegerField(default=1),
        ),
    ]
