# Generated by Django 5.1.4 on 2025-01-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0014_globalexpansion_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourstatistics',
            name='CandidateSatisfactionRate',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ourstatistics',
            name='CandidatesPlaced',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ourstatistics',
            name='ClientRetentionRate',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ourstatistics',
            name='ClientsServed',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ourstatistics',
            name='JoiningRatio',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ourstatistics',
            name='TurnAroundTime',
            field=models.CharField(max_length=4000),
        ),
    ]
