# Generated by Django 5.1.4 on 2025-01-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0015_alter_ourstatistics_candidatesatisfactionrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalexpansion',
            name='i',
        ),
    ]
