# Generated by Django 5.1.4 on 2025-01-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0016_remove_globalexpansion_i'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurStatistics',
        ),
    ]
