# Generated by Django 5.1.4 on 2025-01-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0018_stats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurStatisics',
        ),
        migrations.AlterField(
            model_name='stats',
            name='ClientsServed',
            field=models.IntegerField(),
        ),
    ]
