# Generated by Django 5.1.4 on 2025-01-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0020_alter_stats_candidatesatisfactionrate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientslogos',
            options={'verbose_name': '4 - Our Client'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1 - Range of Service'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': '3 - Our Statistic'},
        ),
    ]
