# Generated by Django 5.1.4 on 2025-01-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0021_alter_clientslogos_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service1_image_url',
            new_name='service1_vedio_url',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service2_image_url',
            new_name='service2_vedio_url',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service3_image_url',
            new_name='service3_vedio_url',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service4_image_url',
            new_name='service4_vedio_url',
        ),
    ]
