# Generated by Django 5.1.4 on 2025-01-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0022_rename_service1_image_url_service_service1_vedio_url_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationsAroundtheWorld',
        ),
        migrations.AlterModelOptions(
            name='globalexpansion',
            options={'verbose_name': '2 - Operations Around the World'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service1_vedio_url',
            new_name='service1_video_url',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service2_vedio_url',
            new_name='service2_video_url',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service3_vedio_url',
            new_name='service3_video_url',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service4_vedio_url',
            new_name='service4_video_url',
        ),
    ]
