# Generated by Django 5.1.4 on 2025-01-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0023_delete_operationsaroundtheworld_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='', max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name': '5 - What Our Clients Say',
            },
        ),
        migrations.DeleteModel(
            name='ClientsResponses',
        ),
    ]
