# Generated by Django 5.1.4 on 2025-01-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0024_clientsresponse_delete_clientsresponses'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': '6 - About PaddleLift',
            },
        ),
        migrations.CreateModel(
            name='MissionAndVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_image_url', models.URLField(default='', max_length=255)),
                ('vision_description', models.TextField()),
                ('mission_image_url', models.URLField(default='', max_length=255)),
                ('mission_description', models.TextField()),
            ],
            options={
                'verbose_name': '7 - Our Vision, Mission & Core Values',
            },
        ),
    ]
