# Generated by Django 5.1.4 on 2025-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0026_rename_vision_description_missionandvision_vission_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('position', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=400)),
                ('linked_in_url', models.URLField(max_length=255)),
                ('about_text', models.TextField()),
                ('image_url', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': '8 - Meet the Management',
            },
        ),
    ]
