# Generated by Django 5.1.4 on 2025-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0027_managementteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': '9 - Life at PaddleLift Images',
            },
        ),
    ]
