# Generated by Django 5.1.4 on 2025-01-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0028_personalimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServicesCescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': '9 - Our Services Description',
            },
        ),
    ]
