# Generated by Django 5.1.4 on 2025-01-26 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0029_ourservicescescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurServicesCescription',
            new_name='OurServicesDescription',
        ),
    ]
