# Generated by Django 5.1.4 on 2025-01-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0030_rename_ourservicescescription_ourservicesdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservicesdescription',
            options={'verbose_name': '10 - Our Services Description'},
        ),
    ]
