# Generated by Django 5.1.4 on 2025-01-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0031_alter_ourservicesdescription_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'F - About PaddleLift'},
        ),
        migrations.AlterModelOptions(
            name='clientslogos',
            options={'verbose_name': 'D - Our Client'},
        ),
        migrations.AlterModelOptions(
            name='clientsresponse',
            options={'verbose_name': 'E - What Our Clients Say'},
        ),
        migrations.AlterModelOptions(
            name='globalexpansion',
            options={'verbose_name': 'B - Operations Around the World'},
        ),
        migrations.AlterModelOptions(
            name='managementteam',
            options={'verbose_name': 'H - Meet the Management'},
        ),
        migrations.AlterModelOptions(
            name='missionandvision',
            options={'verbose_name': 'G - Our Vision, Mission & Core Values'},
        ),
        migrations.AlterModelOptions(
            name='ourservicesdescription',
            options={'verbose_name': 'J - Our Services Description'},
        ),
        migrations.AlterModelOptions(
            name='personalimages',
            options={'verbose_name': 'I - Life at PaddleLift Images'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'A - Range of Service'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'C - Our Statistic'},
        ),
    ]
