# Generated by Django 5.1.4 on 2025-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0032_alter_about_options_alter_clientslogos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustriesWeServeCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_industry', models.TextField()),
            ],
            options={
                'verbose_name': 'L - Industries We Serve Cards',
            },
        ),
        migrations.CreateModel(
            name='IndustriesWeServeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'K - Industries We Serve Description',
            },
        ),
        migrations.CreateModel(
            name='WhatSetsUsApartCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1_heading', models.CharField(max_length=500)),
                ('card1_description', models.TextField()),
                ('card2_heading', models.CharField(max_length=500)),
                ('card2_description', models.TextField()),
                ('card3_heading', models.CharField(max_length=500)),
                ('card3_description', models.TextField()),
                ('card4_heading', models.CharField(max_length=500)),
                ('card4_description', models.TextField()),
            ],
            options={
                'verbose_name': 'M - What Sets Us Apart Cards',
            },
        ),
    ]
