# Generated by Django 5.1.4 on 2025-01-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0033_industriesweservecards_industriesweservedescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=400)),
                ('WhatsApp', models.CharField(max_length=400)),
                ('Email', models.EmailField(max_length=400)),
                ('Address', models.TextField()),
            ],
            options={
                'verbose_name': 'Q - Contact Information',
            },
        ),
        migrations.CreateModel(
            name='FewSuccessStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(default='', max_length=255)),
                ('heading', models.CharField(max_length=500)),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name': 'P - Few Success Stories Cards',
            },
        ),
        migrations.CreateModel(
            name='OrganizationalStructureCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1_heading', models.CharField(max_length=500)),
                ('card1_description', models.TextField()),
                ('card2_heading', models.CharField(max_length=500)),
                ('card2_description', models.TextField()),
                ('card3_heading', models.CharField(max_length=500)),
                ('card3_description', models.TextField()),
                ('card4_heading', models.CharField(max_length=500)),
                ('card4_description', models.TextField()),
            ],
            options={
                'verbose_name': 'N - Organizational Structure Cards',
            },
        ),
        migrations.CreateModel(
            name='OurPortfolioDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'O - Our Portfolio Description',
            },
        ),
    ]
