# Generated by Django 5.1.4 on 2025-01-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page_content', '0035_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'R - Review'},
        ),
    ]
