# Generated by Django 5.1.4 on 2024-12-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone_no',
            field=models.CharField(default='000000000000', max_length=255),
        ),
    ]
