# Generated by Django 5.1.4 on 2025-01-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_cv_email_cv_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
